# Cloudflare Wrangler設定ファイル
name = "demo-ansk"
compatibility_date = "2023-10-30"

# 静的アセットの設定
# 新しいWorkers Static Assets機能を使用
[build]
command = "npm run build"

# ルート設定
# 必要に応じてドメインを設定
# routes = [
#   { pattern = "*", zone_name = "your-domain.com" }
# ]
